const fs = require('fs');
const path = require('path');

const check = () => {
  // Load .env file
  const envPath = path.join(__dirname, '../../.env');
  const schemaPath = path.join(__dirname, '../../env.schema.json');

  const envFile = fs.readFileSync(envPath, 'utf8').toString();
  const schemaFile = fs.readFileSync(schemaPath, 'utf8').toString();

  // Parse .env into key-value pairs
  const envKeys = envFile
    .split('\n')
    .map((line) => line.split('=')[0].trim())
    .filter((key) => key && !key.startsWith('#'));

  // Parse JSON schema
  const schemaKeys = Object.keys(JSON.parse(schemaFile));

  // Find missing and extra keys
  const missingKeys = schemaKeys.filter((key) => !envKeys.includes(key));
  const extraKeys = envKeys.filter((key) => !schemaKeys.includes(key));

  if (missingKeys.length > 0) {
    console.log('Missing keys in .env:', missingKeys);
  } else {
    console.log('No missing keys ✅');
  }

  if (extraKeys.length > 0) {
    console.log('Extra keys in .env:', extraKeys);
  } else {
    console.log('No extra keys ✅');
  }

  return missingKeys;
};

const doctor = () => {
  console.log('👩‍⚕️ PDF Generation: Health Check');

  // check if headless chrome is installed

  // check env values
  check();
};

const args = process.argv.slice(2);

function createEnv() {
  if (fs.existsSync(path.join(__dirname, '../../.env'))) {
    console.log('Environment file already exists checking for missing keys');
    const missingKeys = check();

    if (missingKeys.length) {
      const envPath = path.join(__dirname, '../../.env');

      const envFile = fs.readFileSync(envPath, 'utf-8');

      const schemaPath = path.join(__dirname, '../../env.schema.json');

      const schemaFile = fs.readFileSync(schemaPath, 'utf8');

      const schemaJSON = JSON.parse(schemaFile);

      const autoGeneratedText = '\n## AUTO GENERATED\n';
      const newEnvFileContent = missingKeys.map(
        (key) => `${key} = ${schemaJSON[key]?.example || ''}`,
      );

      const newEnvFile =
        envFile + autoGeneratedText + newEnvFileContent.join('\n') + '\n##';

      try {
        fs.writeFileSync(path.join(__dirname, '../../.env'), newEnvFile);
      } catch (err) {
        console.error('Error generating environment file', err);
      }
    }
  } else {
    try {
      const schemaPath = path.join(__dirname, '../../env.schema.json');

      const schemaFile = fs.readFileSync(schemaPath, 'utf8');

      const schemaJSON = JSON.parse(schemaFile);

      const schemaKeys = Object.keys(schemaJSON);

      const newEnv = schemaKeys.map(
        (key) => `${key} = ${schemaJSON[key]?.example || ''}`,
      );

      fs.writeFileSync(
        path.join(__dirname, '../../.env'),
        '## AUTO GENERATED\n\n' + newEnv.join('\n').toString() + '\n##',
      );
    } catch (err) {
      console.error(err);
    }
  }
}

if (args[0] === 'doctor') doctor();
else if (args[0] === 'genEnv') createEnv();

module.exports = doctor;
